Add clang 8.0.0 libraries to the cxx_builtin_include list
When building using Bazel 0.25.x and toolchain 0.25.0, I get
the following errors:

    ERROR: /home/pedro/.cache/bazel/_bazel_pedro/eb366111355e69c7afe372aacd5d95ad/external/com_github_google_benchmark/BUILD.bazel:11:1: undeclared inclusion(s) in rule '@com_github_google_benchmark//:benchmark':
    this rule is missing dependency declarations for the following files included by 'external/com_github_google_benchmark/src/console_reporter.cc':
      '/usr/local/lib/clang/8.0.0/include/stdint.h'
      '/usr/local/lib/clang/8.0.0/include/stddef.h'
      '/usr/local/lib/clang/8.0.0/include/stdarg.h'
      '/usr/local/lib/clang/8.0.0/include/x86intrin.h'
      '/usr/local/lib/clang/8.0.0/include/ia32intrin.h'
      '/usr/local/lib/clang/8.0.0/include/immintrin.h'
      ...

Adding this folder to the list, fixes the issue